data-visualization/scholia/app/views.py
"""Views for app."""

import re
import json
import os
import urllib.parse

# Original imports from scholia
from flask import (Blueprint, current_app, redirect, render_template, request,
                   Response, url_for)
from werkzeug.routing import BaseConverter

from ..api import entity_to_name, entity_to_smiles, search, wb_get_entities
from ..rss import (wb_get_author_latest_works, wb_get_venue_latest_works,
                   wb_get_topic_latest_works, wb_get_organization_latest_works,
                   wb_get_sponsor_latest_works)
from ..arxiv import metadata_to_quickstatements, string_to_arxiv
from ..arxiv import get_metadata as get_arxiv_metadata
from ..query import (arxiv_to_qs, cas_to_qs, atomic_symbol_to_qs, doi_to_qs,
                     github_to_qs, biorxiv_to_qs, chemrxiv_to_qs,
                     inchikey_to_qs, issn_to_qs, orcid_to_qs, viaf_to_qs,
                     q_to_class, q_to_dois, random_author, twitter_to_qs,
                     cordis_to_qs, mesh_to_qs, pubmed_to_qs,
                     lipidmaps_to_qs, ror_to_qs, wikipathways_to_qs,
                     pubchem_to_qs, atomic_number_to_qs, ncbi_taxon_to_qs,
                     ncbi_gene_to_qs)
from ..utils import sanitize_q
from ..wikipedia import q_to_bibliography_templates

# Custom imports for the Cluster viz
from ..research_commons import (get_keywords_bubble_chart_data, get_author_to_keywords_chart_data,
                                get_keywords_to_authors_chart_data)
                                


class RegexConverter(BaseConverter):
    """Converter for regular expression routes.

    References
    ----------
    https://stackoverflow.com/questions/5870188

    """

    def __init__(self, url_map, *items):
        """Set up regular expression matcher."""
        super(RegexConverter, self).__init__(url_map)
        self.regex = items[0]


def add_app_url_map_converter(self, func, name=None):
    """Register a custom URL map converters, available application wide.

    References
    ----------
    https://coderwall.com/p/gnafxa/adding-custom-url-map-converters-to-flask-blueprint-objects

    """

    def register_converter(state):
        state.app.url_map.converters[name or func.__name__] = func

    self.record_once(register_converter)


Blueprint.add_app_url_map_converter = add_app_url_map_converter
main = Blueprint('app', __name__)
main.add_app_url_map_converter(RegexConverter, 'regex')

# Wikidata item identifier matcher
l_pattern = r'<regex(r"L[1-9]\d*"):lexeme>'
L_PATTERN = re.compile(r'L[1-9]\d*')

q_pattern = r'<regex(r"Q[1-9]\d*"):q>'
q1_pattern = r'<regex(r"Q[1-9]\d*"):q1>'
q2_pattern = r'<regex(r"Q[1-9]\d*"):q2>'
Q_PATTERN = re.compile(r'Q[1-9]\d*')

p_pattern = r'<regex(r"P[1-9]\d*"):p>'
P_PATTERN = re.compile(r'P[1-9]\d*')


# Wikidata item identifiers matcher
qs_pattern = r'<regex(r"Q[1-9]\d*(?:[^0-9]+Q[1-9]\d*)*"):qs>'


@main.route("/")
def index():
    q = "Q106489997"

    first_initial, last_name = '', ''
    return render_template('cluster.html',
                           q=q,
                           first_initial=first_initial,
                           last_name=last_name,
                           cluster_keywords=json.dumps(
                               get_keywords_bubble_chart_data())
                           )

@main.route('/author/' + q_pattern)
def show_author(q):
    """Return HTML rendering for specific author.
    Parameters
    ----------
    q : str
        Wikidata item identifier.
    Returns
    -------
    html : str
        Rendered HTML.
    """
    entities = wb_get_entities([q])
    name = entity_to_name(entities[q])
    if name:
        first_initial, last_name = name[0], name.split()[-1]
    else:
        first_initial, last_name = '', ''
    return render_template('author.html', q=q, first_initial=first_initial,
                           last_name=last_name)

@main.route('/author/')
def show_author_empty():
    """Return author index page.
    Returns
    -------
    html : str
        Rendered index page for author view.
    """
    return render_template('author_empty.html')                           


@main.route('/keyword')
def show_keyword():
    query_keyword = request.args.get('kw')
    n_keywords = int(request.args.get('n'))

    first_initial, last_name = '', ''
    return render_template('keyword.html',
                           q=query_keyword,
                           first_initial=first_initial,
                           last_name=last_name,
                           cluster_keywords=json.dumps(get_keywords_to_authors_chart_data(
                               query_keyword, 1, n_keywords))
                           )


@main.route('/keyword/author')
def show_keyword_of_author():
    author = request.args.get('name')

    first_initial, last_name = '', ''
    return render_template('keyword_author.html',
                           q=author,
                           first_initial=first_initial,
                           last_name=last_name,
                           cluster_keywords=json.dumps(
                               get_author_to_keywords_chart_data(author))
                           )

                     


@main.route("/" + l_pattern)
def redirect_l(lexeme):
    """Redirect to Scholia lexeme aspect.

    Parameters
    ----------
    lexeme : str
        Wikidata lexeme identifier

    """
    return redirect(url_for('app.show_lexeme', lexeme=lexeme), code=302)


@main.route("/" + q_pattern)
def redirect_q(q):
    """Detect and redirect to Scholia class page.

    Parameters
    ----------
    q : str
        Wikidata item identifier

    """
    class_ = q_to_class(q)
    method = 'app.show_' + class_
    return redirect(url_for(method, q=q), code=302)


@main.route("/" + p_pattern)
def show_p(p):
    """Detect and redirect to Scholia class page.

    Parameters
    ----------
    p : str
        Wikidata property identifier

    """
    return render_template('property.html', p=p)


@main.route('/biorxiv/<biorxiv_id>')
def show_biorxiv(biorxiv_id):
    """Return HTML rendering for bioRxiv.

    Parameters
    ----------
    biorxiv_id : str
        bioRxiv identifier.

    Returns
    -------
    html : str
        Rendered HTML.

    """
    qs = biorxiv_to_qs(biorxiv_id)
    return _render_work_qs(qs)


@main.route('/chemrxiv/<chemrxiv_id>')
def show_chemrxiv(chemrxiv_id):
    """Return HTML rendering for ChemRxiv.

    Parameters
    ----------
    chemrxiv_id : str
        ChemRxiv identifier.

    Returns
    -------
    html : str
        Rendered HTML.

    """
    qs = chemrxiv_to_qs(chemrxiv_id)
    return _render_work_qs(qs)


@main.route('/arxiv/<arxiv>')
def show_arxiv(arxiv):
    """Return HTML rendering for arxiv.

    Parameters
    ----------
    arxiv : str
        Arxiv identifier.

    Returns
    -------
    html : str
        Rendered HTML.

    See Also
    --------
    show_arxiv_to_quickstatements.

    """
    qs = arxiv_to_qs(arxiv)
    return _render_work_qs(qs)


def _render_work_qs(qs):
    if len(qs) > 0:
        q = qs[0]
        return redirect(url_for('app.show_work', q=q), code=302)
    return render_template('404.html')


@main.route('/arxiv-to-quickstatements')
def show_arxiv_to_quickstatements():
    """Return HTML rendering for arxiv.

    Will look after the 'arxiv' parameter.

    Returns
    -------
    html : str
        Rendered HTML.

    See Also
    --------
    show_arxiv.

    """
    query = request.args.get('arxiv')

    if not query:
        return render_template('arxiv_to_quickstatements.html')

    current_app.logger.debug("query: {}".format(query))

    arxiv = string_to_arxiv(query)
    if not arxiv:
        # Could not identify an arxiv identifier
        return render_template('arxiv_to_quickstatements.html')

    qs = arxiv_to_qs(arxiv)
    if len(qs) > 0:
        # The arxiv is already in Wikidata
        q = qs[0]
        return render_template('arxiv_to_quickstatements.html',
                               arxiv=arxiv, q=q)

    try:
        metadata = get_arxiv_metadata(arxiv)
    except Exception:
        return render_template('arxiv_to_quickstatements.html',
                               arxiv=arxiv)

    quickstatements = metadata_to_quickstatements(metadata)

    # For Quickstatements Version 2 in URL components,
    # TAB and newline should be replace by | and ||
    # https://www.wikidata.org/wiki/Help:QuickStatements
    # Furthermore the '/' also needs to be encoded, but Jinja2 urlencode does
    # not encode that character.
    # https://github.com/pallets/jinja/issues/515
    # Here, we let jinja2 handle the encoding rather than adding an extra
    # parameter
    return render_template('arxiv_to_quickstatements.html',
                           arxiv=arxiv, quickstatements=quickstatements)


@main.route('/faq')
def show_faq():
    """Return rendered FAQ page.

    Returns
    -------
    html : str
        Rendered HTML page for FAQ page.

    """
    return render_template('faq.html')


@main.route('/search')
def show_search():
    """Return search page.

    Returns
    -------
    html : str
        Rendered index page for search view.

    """
    query = request.args.get('q', '')
    if query:
        search_results = search(query)
    else:
        search_results = []
    return render_template('search.html',
                           query=query, search_results=search_results)


@main.route('/about')
def show_about():
    """Return rendered about page.

    Returns
    -------
    html : str
        Rendered HTML page for about page.

    """
    return render_template('about.html')


@main.route('/favicon.ico')
def show_favicon():
    """Detect and redirect for the favicon.ico."""
    return redirect(url_for('static', filename='favicon/favicon.ico'))


@main.route('/doi/<path:doi>')
def redirect_doi(doi):
    """Detect and redirect for DOI.
    Parameters
    ----------
    doi : str
        DOI identifier.
    """

data-visualization/scholia/app/templates/404_doi.html
{% extends "base.html" %}

{% block page_content %}

There was no work found with DOI <a href="https://doi.org/{{ doi }}">{{ doi }}</a>.

<script src="{{ url_for('static', filename='js/citation.js') }}"></script>

<h2>QuickStatements</h2>

<pre class="citation-js" data-input="{{ doi }}" data-output-format="quickstatements"></pre>

{% endblock %}

data-visualization/scholia/app/templates/about.html
{% extends "base.html" %}

{% block page_content %}
<h1 id="h1">About</h1>

<h2>Background reading</h2>

<ul>
    <li><a href="https://arxiv.org/pdf/1703.04222">Scholia and scientometrics with Wikidata</a>.</li>
    <li><a href="https://finnaarupnielsen.wordpress.com/2016/09/21/so-what-can-we-use-wikicite-for/">So what can we use Wikicite for?</a></li>
    <li><a href="https://finnaarupnielsen.wordpress.com/2016/09/30/the-wikidata-scholarly-profile-page/">The Wikidata scholarly profile page</a></li>
    <li><a href="https://meta.wikimedia.org/wiki/File:WikiCite_2016_report.pdf">WikiCite 2016 Report</a></li>
    <li><a href="https://riojournal.com/article/35820/">Robustifying Scholia: paving the way for knowledge discovery and research assessment through Wikidata</a></li>
</ul>

<h2>FAQ</h2>

<ul>
    <li>See the <a href="https://scholia.toolforge.org/faq">dedicated page</a>.</li>
</ul>

<h3>Presentations</h3>

<ul>
  <li><a href="http://mirror.netcologne.de/CCC/events/wikidatacon/2017/h264-hd/wikidatacon2017-10010-eng-Scholia_hd.mp4">Scholia</a>.
    35 minute presentation including discussion at WikidataCon 2017, Berlin, Germany.</li>
  <li><a href="http://mirror.netcologne.de/CCC/events/wikidatacon/2017/h264-hd/wikidatacon2017-10013-eng-Describing_Software_So_We_Can_Cite_Software_hd.mp4">Describing software so we can cite software</a>.
    11 minute part of presentation and discussion at WikidataCon 2017,
    Berlin, Germany.</li>
</ul>


<h2>Acknowledgment</h2>

<ul>
    <li>Scholia has received funding from:<br />
        <ul>
            <li>the Alfred P. Sloan Foundation under grant number <a href="https://sloan.org/grant-detail/8961">G-2019-11458</a></li>
        </ul>
    </li>
    <li><a href="https://meta.wikimedia.org/wiki/WikiCite">Wikicite</a>.</li>
    <li>Lambert Heller. Inspiration from <a href="http://blogs.lse.ac.uk/impactofsocialsciences/2015/07/16/scholarly-profile-of-the-future/">What will the scholarly profile page of the future look like? Provision of metadata is enabling experimentation</a>.</li>
    <li>Egon Willighagen, <a href="https://twitter.com/egonwillighagen/status/784473926944563200">ORCID idea</a>.</li>
    <li>Magnus Manske.</li>
    <li>Jakob Voß.</li>
    <li>Shubhanshu Mishra, <a href="https://twitter.com/TheShubhanshu/status/792752931347062784">inspiration</a> for author profile visualization with LEGOLAS, see, e.g., <a href="http://abel.lis.illinois.edu/legolas/profile_basic">the example for Neil Smalheiser</a>.</li>
</ul>


<h3>Technical acknowledgement</h3>

<ul>
    <li><a href="http://flask.pocoo.org/">Flask</a>, python web framework (<a href="http://flask.pocoo.org/docs/0.12/license/">BSD license).</li>
	<li><a href="https://getbootstrap.com/">Bootstrap</a>, front-end framework (<a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">MIT license</a>).</li>
	<li><a href="https://jquery.com/">jQuery</a>, Javascript library (<a href="https://jquery.org/license/">jQuery license</a>, typically MIT license).</li>
  <li><a href="https://datatables.net/">DataTables</a>, table-rendering Javascript library (MIT license).</li>
  <li><a href="https://glyphicons.com/">Glyphicon</a> Halflings</li>
  <li>...</li>
</ul>


<h2>Citation</h2>

<pre>
@InProceedings{NielsenF2017Scholia,
  author = 	 {Finn {\AA}rup Nielsen and Daniel Mietchen and Egon
                  Willighagen},  
  title = 	 {Scholia and scientometrics with Wikidata},
  booktitle =    {Scientometrics 2017},
  year = 	 {2017},
  arxiv =        {1703.04222},
  wikidata =     {Q28942417},
  URL =          {https://arxiv.org/pdf/1703.04222},
}
</pre>


{% endblock %}
    

data-visualization/scholia/app/templates/arxiv_to_quickstatements.html
{% extends "base.html" %}


{% block page_content %}

<h1>arXiv to QuickStatements</h1>


<h2>Input</h2>

<form action="" id="form" method="GET" class="form-horizontal">
  <div class="input-group">
    {% if arxiv %}
    <input type="text" class="form-control" placeholder="Enter arXiv id" value="{{ arxiv | urlencode }}" id="searchterm" name="arxiv"/>
    {% else %}
    <input type="text" class="form-control" placeholder="Enter arXiv id" id="searchterm" name="arxiv"/>
    {% endif %}
    <span class="input-group-btn">
      <button class="btn btn-primary" type="submit">
        Extract metadata
      </button>
    </span>
  </div>
</form>
    
<p>Copy and paste an ID from the <a href="https://arxiv.org">arXiv</a> preprint repository.
Bare IDs (such as "1703.06103") and URLs (such as "https://arxiv.org/abs/1703.06103") both work.
</p>
<p>The input ID will be queried in Wikidata and Quickstatements will not be generated if the input 
ID is found in Wikidata. However, note that new items may not be immediately found because of caching.


<h2>Result</h2>

{% if q %}

<div id="searchresult">Already entered as <a href="work/{{ q }}">{{ q }}</div>

{% endif %}

{% if quickstatements %}

<div id="quickstatements"><pre>{{ quickstatements }}</pre></div>

<a href="https://quickstatements.toolforge.org/#/v1={{ quickstatements | replace('\t', '|') | replace('\n', '||') | urlencode | replace('/','%2F') }}">
  <button class="btn btn-primary">Submit to Quickstatements ↗</button>
</a>
  
{% endif %}


{% endblock %}

data-visualization/scholia/app/templates/bootstrap-base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
    <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

data-visualization/scholia/app/templates/catalogue_empty.html
{% extends "base.html" %}

{% block page_content %}

<h1>Catalogue</h1>


<h2>Examples</h2>

<dl>
    <dt><a href="Q42661788">Dansk Guldalder Maleri</a></dt>
    <dd>
	[Danish Golden Age Painting].
	A catalogue from the <em>Ny Carlsberg Glyptotek</em> art callery
	in Copenhagen detailing paintings by Danish artists in 
	the period 1800&ndash;1850 (circa).
    </dd>

    <dt><a href="Q51456640">De 20 højeste lønninger på KU i 2017</a></dt>
    <dd>
	[The 20 highest salaries at University of Copenhagen in 2017].
	A short list of administrators and prominent researchers from a university in Denmark.
    </dd>

    <dt><a href="Q51467536">What are the ten most cited sources on Wikipedia? Let’s ask the data</a></dt>
    <dd>
	A short list of scientific papers and books including
	reference works that are highly cited from Wikipedias.
    </dd>
</dl>


{% endblock %}

  

data-visualization/scholia/app/templates/cluster.html
{% extends "base.html" %}

{% set aspect = "cluster" %}

{% block in_ready %}


{{ sparql_to_table('cluster-members') }}

{{ sparql_to_table('publications') }}

{{ sparql_to_iframe('publications-per-year') }}

{{ sparql_to_iframe('publications-per-year-and-author') }}

{{ sparql_to_iframe('wiki-topics') }}

{{ sparql_to_iframe('venue-statistics') }}

{{ sparql_to_table('venue-year-stats') }}

{% endblock %}

{% block scripts %}
{{super()}}

<script type="text/javascript" src="{{ url_for('static', filename='d3.v3.5.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='underscore-umd-min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='dimple.v2.3.0.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='vis-network.min.js') }}"></script>




<!-- Charts used by wikidata query service, @see: https://github.com/wikimedia/wikidata-query-gui -->
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/getMessage.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/FormatterHelper.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/Options.js') }}"></script>
<!-- Abstract data used by all charts  -->
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/AbstractResultBrowser.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/AbstractChartResultBrowser.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/AbstractDimpleChartResultBrowser.js') }}"></script>
<!-- Bar chart -->
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/BarChartResultBrowser.js') }}"></script>
<!-- Bubble chart -->
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/BubbleChartResultBrowser.js') }}"></script>
<!-- Graph chart -->
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/GraphResultBrowserNodeBrowser.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='wikidata/GraphResultBrowser.js') }}"></script>

<script type="text/javascript">
// https://codepen.io/mikuel/pen/amXXBN

$( document ).ready(function() {

// https://stackoverflow.com/questions/58224221/send-json-string-from-python-app-to-javascript-in-jinja-template
var bubbleChartData = JSON.parse({{ cluster_keywords|tojson }});


// var wdqsTable = new wikibase.queryService.ui.resultBrowser.TableResultBrowser();
var wdqsBubbleChart = new wikibase.queryService.ui.resultBrowser.BubbleChartResultBrowser();
var wdqsGraphChart = new wikibase.queryService.ui.resultBrowser.GraphResultBrowser();

wdqsBubbleChart.setResult(bubbleChartData);
wdqsBubbleChart.draw($('#keywords-chart'));

});

</script>

{% endblock %}


{% block page_content %}

<a href="https://water.ubc.ca/" target="_blank"><img src="{{ url_for('static', filename='images/ubc_futurewaters_logo_sm.jpg') }}" width="210px" height="119px" alt="Future Waters Cluster"></a>
<h1 id="h1">Author</h1>



<!-- <div id="chart"></div> -->



<div id="intro"></div>

<div id="wembedder"></div>

<div id="details"></div>



<h3 id="cluster-members-header">Cluster Members</h3>

Information automaticaly gathered from wikidata. Please refer to 
<a href="https://water.ubc.ca/home" target="_blank">Future waters</a> for the complete list of cluster members.

<p><button type="button" class="btn btn-warning btn-circle"><i class="fa fa-question"></i></button> Use the search bar to find information about a cluster member</p>

<table class="table table-hover" id="cluster-members-table"></table>


<br>
<br>
<hr>

<h3 id="publications-header">Publications</h3>

<p><button type="button" class="btn btn-warning btn-circle"><i class="fa fa-question"></i></button> Use the search to filter results based on any of the columns in the table</p>

<table class="table table-hover" id="publications-table"></table>

<br>
<br>
<hr>



<h3 id="keywords-chart-header">Keywords</h3>

<p><button type="button" class="btn btn-info btn-circle"><i class="fa fa-exclamation"></i></button> These keywords are derived from our custom data-gathering scripts</p>
<p><button type="button" class="btn btn-warning btn-circle"><i class="fa fa-question"></i></button> Click on a keyword to find information about it and its cluster members</p>



<div>
    <div id="keywords-chart"></div>
</div>

<br>
<br>
<hr>

<p><button type="button" class="btn btn-info btn-circle"><i class="fa fa-exclamation"></i></button> These keywords are derived from Wikidata</p>

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" id="wiki-topics-iframe"></iframe>
</div>


<br>
<br>
<hr>

<h2 id="venue-statistics-header">Venue statistics</h2>

<p><button type="button" class="btn btn-warning btn-circle"><i class="fa fa-question"></i></button> Hove over a bubble to see the total number of publications for that venue</p>

<div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" id="venue-statistics-iframe"></iframe>
</div>

<br>
<br>
<hr>

<p>Venue publication count per year.</p>
<p><button type="button" class="btn btn-warning btn-circle"><i class="fa fa-question"></i></button> Use the search bar to find information about a specific year or veneu</p>


<table class="table table-hover" id="venue-year-stats-table"></table>

<br>
<br>
<hr>

<h2 id="publications-per-year-header">Publications per year</h2>

<p><button type="button" class="btn btn-warning btn-circle"><i class="fa fa-question"></i></button> Hove over a bar to see the total number of publications on that year</p>

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" id="publications-per-year-iframe"></iframe>
</div>

<h3>Detailed list of publications per year and authors</h3>

<p><button type="button" class="btn btn-warning btn-circle"><i class="fa fa-question"></i></button> Hove over a bar to see an author's name and their total number of publications on that year</p>

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" id="publications-per-year-and-author-iframe"></iframe>
</div>





{% endblock %}

data-visualization/scholia/app/templates/cluster_base.html
{% extends "base.html" %}

{% block navbar %}
<div class="navbar navbar-static-top">
    <ul class="nav nav-pills">
	<li role="presentation"><a href="{{ url_for('app.index') }}">Scholia</a></li>
	<li role="presentation" class="active"><a href="{{ url_for('app.show_author_empty') }}">Author</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_work_empty') }}">Work</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_organization_empty') }}">Organization</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_venue_empty') }}">Venue</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_series_empty') }}">Series</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_publisher_empty') }}">Publisher</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_sponsor_empty') }}">Sponsor</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_award_empty') }}">Award</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_topic_empty') }}">Topic</a></li>
	<li role="presentation"><a href="{{ url_for('app.show_about') }}">About</a></li>
    </ul>
</div>
{% endblock %}

data-visualization/scholia/app/templates/favicon.html
<!-- Generated with RealFaviconGenerator -->
<link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
<link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
<link rel="mask-icon" href="{{ url_for('static', filename='favicon/safari-pinned-tab.svg') }}" color="#09af8a">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
<meta name="apple-mobile-web-app-title" content="Scholia">
<meta name="application-name" content="Scholia">
<meta name="msapplication-TileColor" content="#09af8a">
<meta name="theme-color" content="#09af8a">

data-visualization/scholia/app/templates/lexeme.html
{% extends "base.html" %}

{% set aspect = "lexeme" %}

{% block in_ready %}

{{ sparql_to_table('works') }}

{% endblock %}

{% block page_content %}

<p>
    <a title="Lexeme index"
       role="button"
       class="btn btn-outline-dark btn-sm"
       href="../lexeme">←</a>
    <a title="View and edit lexeme in Wikidata"
       role="button"
       class="btn btn-outline-dark btn-sm"
       href="https://www.wikidata.org/wiki/Lexeme:{{ lexeme }}">Wikidata 🔗</a>
    <a title="View lexeme in Ordia"
       role="button"
       class="btn btn-outline-dark btn-sm"
       href="https://ordia.toolforge.org/{{ lexeme }}">Ordia 🔗</a>
</p>

<h1 id="h1">Lexeme</h1>

<h2 id="works-header">Works</h2>

<table class="table table-hover" id="works-table"></table>

{% endblock %}